(function(){function trigger_box(it
/**/) {
var out='<div class="sensors-jssdk-trigger-box-out"> <div class="sensors-jssdk-trigger-box-header sensors-jssdk-clearfix"> <button class="sensors-jssdk-trigger-box-deploy-btn" style="background:#19b27b;border:none;border-radius: 4px;color: #fff;float: right;padding: 6px;cursor: pointer;font-size:14px;font-weight:bold;">部署生效</button> <span class="sensors-jssdk-trigger-box-header-title-change">您有新的改动，需要部署才能生效</span> </div> <div class="sensors-jssdk-trigger-box-content"> <ul> '; for(var key in it) {  out+=' <li class="sensors-jssdk-trigger-box-content-li"> <div class="sensors-jssdk-clearfix sensors-jssdk-trigger-box-content-title"> <!--<span class="sensors-jssdk-trigger-box-content-delete"> X </span>--> <span>'+(it[key].cname || '' )+((' ( '+it[key].name+' ) ' )|| '')+'</span> </div> <ul class="sensors-jssdk-trigger-box-content-list"> ';var arr1=it[key].triggers;if(arr1){var obj,index=-1,l1=arr1.length-1;while(index<l1){obj=arr1[index+=1];out+=' <li class="sensors-jssdk-clearfix ';if((obj.to_del || !obj.deployed)){out+='sensors-jssdk-trigger-box-attention-red';}out+='" data-trigger="'+(String(obj.trigger_id))+'" data-deploy="'+(String(obj.deployed))+'">  ';if(obj.to_del){out+=' <span class="sensors-jssdk-trigger-box-left-sign"> — </span> <span class="sensors-jssdk-trigger-box-condition"><strike>点击 '+((obj.nthEle.join(' ') + (obj.selfAttr.text ? '且包含内容'+obj.selfAttr.text : '') ))+'</strike></span> ';}else if(obj.deployed){out+=' <span class="sensors-jssdk-trigger-box-left-sign" style="visibility: hidden;"> ＝ </span> <span class="sensors-jssdk-trigger-box-condition">点击 '+((obj.nthEle.join(' ') + (obj.selfAttr.text ? '且包含内容'+obj.selfAttr.text : '') ))+'</span> ';}else{out+=' <span class="sensors-jssdk-trigger-box-left-sign"> ＋ </span> <span class="sensors-jssdk-trigger-box-condition">点击 '+((obj.nthEle.join(' ') + (obj.selfAttr.text ? '且包含内容'+obj.selfAttr.text : '') ))+'</span> ';}out+=' ';if(!obj.to_del){out+=' <span class="sensors-jssdk-trigger-box-content-delete"> 删除 </span> ';}else{out+=' <span class="sensors-jssdk-trigger-box-content-revert"> 恢复 </span> ';}out+=' </li> ';} } out+=' </ul> </li> '; } out+=' </ul> </div></div>';return out;
}var itself=trigger_box, _encodeHTML=(function (doNotSkipEncoded) {
		var encodeHTMLRules = { "&": "&#38;", "<": "&#60;", ">": "&#62;", '"': "&#34;", "'": "&#39;", "/": "&#47;" },
			matchHTML = doNotSkipEncoded ? /[&<>"'\/]/g : /&(?!#?\w+;)|<|>|"|'|\//g;
		return function(code) {
			return code ? code.toString().replace(matchHTML, function(m) {return encodeHTMLRules[m] || m;}) : "";
		};
	}());doT.gtemplate = doT.gtemplate || {};doT.gtemplate['trigger_box'] = itself;}());